import os
import subprocess
import shutil
import glob
import sys

REFERENCE_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(REFERENCE_DIR)

IRIS_REPO = "https://github.com/IrisShaders/Iris.git"
IRIS_DIR = os.path.join(REFERENCE_DIR, "iris_src")
MC_DIR = os.path.join(REFERENCE_DIR, "minecraft_src")

def run_cmd(cmd, cwd=None):
    print(f"Running: {cmd}")
    subprocess.run(cmd, shell=True, check=True, cwd=cwd)

def handle_remove_readonly(func, path, exc):
    import stat
    excvalue = exc[1]
    if func in (os.rmdir, os.remove, os.unlink) and excvalue.errno == 13:
        os.chmod(path, stat.S_IRWXU| stat.S_IRWXG| stat.S_IRWXO)
        func(path)
    else:
        raise

def setup_iris():
    print("\n=== Setting up Iris Source ===")
    if os.path.exists(IRIS_DIR):
        print("Removing old iris_src directory...")
        shutil.rmtree(IRIS_DIR, onerror=handle_remove_readonly)
            
    if not os.path.exists(IRIS_DIR):
        print("Cloning Iris repository (depth 1)...")
        run_cmd(f"git clone --depth 1 {IRIS_REPO} {IRIS_DIR}")

def setup_minecraft():
    print("\n=== Setting up Minecraft Source (Class files and Assets) ===")
    if os.path.exists(MC_DIR):
        print("Removing old minecraft_src directory...")
        shutil.rmtree(MC_DIR, onerror=handle_remove_readonly)
    
    os.makedirs(MC_DIR, exist_ok=True)
    
    # Try to find the Minecraft jar generated by Fabric Loom
    search_pattern = os.path.join(PROJECT_ROOT, "tachyon-mod", ".gradle", "loom-cache", "minecraftMaven", "net", "minecraft", "minecraft-merged-*", "**", "*.jar")
    jars = glob.glob(search_pattern, recursive=True)
    
    if not jars:
        print("ERROR: Could not find Minecraft jar in tachyon-mod/.gradle/loom-cache. Have you run the gradle build yet?")
        sys.exit(1)
        
    # Pick the most recently modified jar if multiple exist
    mc_jar = max(jars, key=os.path.getctime)
    # Fix paths for WSL if using bash unzip, or use python's zipfile
    print(f"Found Minecraft jar: {mc_jar}")
    
    print("Extracting jar using Python zipfile module...")
    import zipfile
    with zipfile.ZipFile(mc_jar, 'r') as zip_ref:
        zip_ref.extractall(MC_DIR)
    print("Minecraft extraction complete.")

if __name__ == "__main__":
    print("=== Tachyon Reference Generator ===")
    setup_iris()
    setup_minecraft()
    print("\nAll references generated successfully in .reference/")
