[workspace]
name = "test-shader"
version = "0.1.0"
description = "Mojo 1.0 SPIR-V Test Shader"
authors = ["Annhilati"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
platforms = ["linux-64", "osx-arm64"]

[dependencies]
mojo = ">=1.0.0"
llvm-spirv = ">=22.1.2,<23"
llvm = ">=22.1.8,<23"
llvm-tools = ">=22.1.8,<23"
spirv-tools = ">=2026.3,<2027"

[tasks]
build = "bash ../tachyon-sdk/compiler/build.sh" # This is a placeholder command for compiling to SPIR-V
