[workspace]
name = "test-shader"
version = "0.1.0"
description = "Mojo 1.0 SPIR-V Test Shader"
authors = ["Annhilati"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
platforms = ["linux-64", "osx-arm64"]

[dependencies]
mojo = "*"

[tasks]
build = "cd ../tachyon-sdk-mojo && pixi run mojo run tachyon/_cli.mojo ../test-shader-mojo/shader.mojo -o ../test-shader-mojo/dummy/post_desaturate.spv"
clean = "rm -f dummy/*.spv tachyon_post.spv"
