[workspace]
name = "test-shader"
version = "0.1.0"
description = "Mojo 1.0 SPIR-V Test Shader"
authors = ["Annhilati"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
platforms = ["linux-64", "osx-arm64"]

[dependencies]
mojo = "*"
python = ">=3.14.7,<3.15"

[tasks]
build = "cd ../tachyon-sdk-mojo && ~/.pixi/bin/pixi run ./tachyon_compiler ../test-shader-mojo/shader.mojo -o ../tachyon-mod/run/shaderpacks/shader"
clean = "rm -f dummy/*.spv tachyon_post.spv"
